APP:
  ENVIRONMENT: test
  DEBUG: True
  API_KEY:  'dd764c65e8685d30f05dddbe0f2f9e04'
  BASE_URL: 'https://api.themoviedb.org/3/'

DATABASE:
  DATABASE_URL: 'postgresql+pg8000://postgres:postgres@localhost:5432/movie'
  USERNAME: moraghan
  PASSWORD:
  HOST: 127.0.0.1
  PORT: 5432
  DB: movies

TMDB_REQUEST_TYPES:
  movie:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api.themoviedb.org/3/movie/{id}?api_key={api_key}'
  person:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api.themoviedb.org/3/person/{id}?api_key={api_key}'
  collection:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api.themoviedb.org/3/collection/{id}?api_key={api_key}'
  company:
    MAX_REQUEST_KEY: 100000
    URL: 'https://api.themoviedb.org/3/company/{id}?api_key={api_key}'
  credit:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api.themoviedb.org/3/movie/{id}/credits?api_key={api_key}'
  keyword:
    MAX_REQUEST_KEY: 100000
    URL: 'https://api.themoviedb.org/3/keyword/{id}?api_key={api_key}'


